import {chromium,expect} from '@playwright/test';
import assert from 'node:assert/strict';
import {readingEmotions} from '../src/lib/reading-emotions';
const base=process.env.READER_URL??'http://127.0.0.1:3101';
const browser=await chromium.launch({channel:'chrome',headless:true});
try{
 const page=await browser.newPage({viewport:{width:1440,height:900}}),errors:string[]=[];
 page.on('pageerror',e=>errors.push(e.message));
 const calls:{target:string;precedingContext:string;followingContext:string}[]=[];
 let active=0,maxActive=0;
 await page.route('**/api/custom-emotions',async route=>{
  if(route.request().method()==='GET'){await route.fulfill({json:{guest:true,jevAvailable:true}});return;}
  const {sentence}=route.request().postDataJSON();calls.push(sentence);active++;maxActive=Math.max(maxActive,active);
  await new Promise(resolve=>setTimeout(resolve,100));active--;
  await route.fulfill({json:{scores:Object.fromEntries(readingEmotions.map(e=>[e,e==='joy'||e==='trust'?.9:.1])),remaining:1000-calls.length}});
 });
 await page.goto(`${base}/your-text`);
 await expect(page.getByRole('heading',{name:'My texts'})).toBeVisible();
 const editor=page.locator('.cm-content');await editor.click();
 const story=Array.from({length:70},(_,i)=>`Sentence ${i+1} brings a small surprise to the room.`).join(' ');
 await page.keyboard.insertText(story);
 await expect.poll(()=>calls.length).toBeGreaterThan(0);
 assert(calls.length<70,'Analysis should be scoped to the visible editor viewport');
 assert(maxActive<=6,'Client must respect its six-request bound');
 await expect(page.locator('[data-jev-highlight]').first()).toBeVisible();
 await expect(page.getByText(/of 70 sentences analysed/)).toBeVisible();
 const beforeDial=calls.length;
 await page.getByLabel('How emotional is JEV',{exact:true}).fill('100');
 await page.waitForTimeout(300);
 assert.equal(calls.length,beforeDial,'Threshold changes reuse scores');
 await page.getByRole('button',{name:'Anger',exact:true}).hover();
 await expect(page.locator('.emotion-tooltip').filter({hasText:'Anger'})).toBeVisible();
 await page.locator('[data-jev-highlight]').first().hover();
 await expect(page.locator('.custom-emotion-tooltip')).toBeVisible();
 await expect(page.locator('.custom-emotion-tooltip')).toContainText('Joy');
 await expect(page.locator('.custom-emotion-tooltip')).toContainText('Trust');
 await page.screenshot({path:'/tmp/jev-your-text-desktop.png'});
 const beforeScroll=calls.length;
 await page.locator('.cm-scroller').evaluate(element=>{element.scrollTop=element.scrollHeight;});
 await expect.poll(()=>calls.length).toBeGreaterThan(beforeScroll);
 await page.setViewportSize({width:390,height:844});
 await page.getByRole('button',{name:'Overview'}).click();
 await expect(page.getByRole('heading',{name:'Emotion overview'})).toBeVisible();
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Mobile content fits viewport');
 await page.screenshot({path:'/tmp/jev-your-text-mobile.png'});
 await page.getByRole('button',{name:'Controls'}).click();
 await expect(page.getByRole('heading',{name:'My texts'})).toBeVisible();
 await page.screenshot({path:'/tmp/jev-your-text-mobile-controls.png'});
 await page.getByRole('button',{name:'Close controls'}).click();
 await page.screenshot({path:'/tmp/jev-your-text-mobile-main.png'});
 const draft=await page.evaluate(()=>sessionStorage.getItem('jev-your-text-draft'));
 assert(draft?.includes('Sentence 1'),'Guest draft survives navigation in this tab');
 await page.reload();
 await expect(page.locator('.cm-content')).toContainText('Sentence 1');
 await page.locator('.cm-content').click();
 await page.keyboard.press('ControlOrMeta+A');
 await page.keyboard.insertText('x'.repeat(20_001));
 await expect(page.locator('.custom-limit-error')).toContainText('20,000 characters');
 await expect(page.locator('.cm-content')).toContainText('Sentence 1');
 assert.deepEqual(errors,[]);
 console.log(JSON.stringify({status:'passed',mockedJev:true,calls:calls.length,maxConcurrent:maxActive}));
}finally{await browser.close();}
