import {chromium,expect} from '@playwright/test';
import assert from 'node:assert/strict';
import {readingEmotions,readingRequestConcurrency} from '../src/lib/reading-emotions';
const base=process.env.READER_URL??'http://127.0.0.1:3101';
const browser=await chromium.launch({channel:'chrome',headless:true});
try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 const calls:{layer:string;sentenceId:string}[]=[];let active=0,maxActive=0,failOnce=true;
 await page.route('**/api/emotions?*',async route=>{const r=await route.fetch();const d=await r.json();assert(r.ok(),d.error);await route.fulfill({json:{...d,jevAvailable:true}});});
 await page.route('**/api/emotions',async route=>{
  const body=route.request().postDataJSON();calls.push(body);active++;maxActive=Math.max(maxActive,active);
  await new Promise(r=>setTimeout(r,120));active--;
  if(failOnce){failOnce=false;await route.fulfill({status:502,json:{error:'Fixture: temporary model failure.'}});return;}
  await route.fulfill({json:{sentenceId:body.sentenceId,scores:Object.fromEntries(readingEmotions.map(e=>[e,e==='fear'||e==='trust'?.9:.1]))}});
 });
 await page.goto(base);await page.locator('[data-emotion-id]').last().waitFor();
 await expect(page.getByRole('button',{name:'Retry analysis'})).toBeVisible();await page.getByRole('button',{name:'Retry analysis'}).click();
 await expect(page.locator('[data-jev-highlight]').first()).toBeVisible();
 assert(maxActive<=readingRequestConcurrency);assert(maxActive>2,'Nearby work should use the expanded concurrency');assert(calls.length>0&&calls.length<100,'Only nearby sentences should be requested');
 await page.getByRole('button',{name:'Fear',exact:true}).scrollIntoViewIfNeeded();await page.waitForTimeout(1200);
 const firstCalls=calls.length;
 await expect(page.getByRole('group',{name:'Visible emotions'}).getByRole('button',{pressed:true})).toHaveCount(8);await expect(page.locator('[data-jev-highlight]').first()).toHaveAttribute('data-jev-highlight','fear trust');await page.getByRole('button',{name:'Fear',exact:true}).click();await expect(page.locator('[data-jev-highlight]').first()).toHaveAttribute('data-jev-highlight','trust');await page.waitForTimeout(350);assert.equal(calls.length,firstCalls,'Changing emotion must reuse scores');
 const marked=page.locator('[data-jev-highlight]').first();
 await marked.hover();await expect(marked.locator('.emotion-hint')).toHaveCSS('opacity','1');await expect(marked.locator('.emotion-hint'),'Only the visible emotions appear in the hover guidance').toHaveText('Trust');
 // Marked sentences are not clickable: hover and keyboard focus are the only routes to the guidance.
 assert.equal(await marked.getAttribute('role'),null);assert.equal(await page.getByLabel('Emotion inspection',{exact:true}).count(),0);
 await page.mouse.move(0,0);await expect(marked.locator('.emotion-hint')).toHaveCSS('opacity','0');
 await page.keyboard.press('Escape');await marked.focus();
 assert(await page.evaluate(()=>!!(document.activeElement as HTMLElement)?.dataset.emotionId));
 await expect(marked.locator('.emotion-hint')).toHaveCSS('opacity','1');
 await page.keyboard.press('Escape');
 await page.getByRole('button',{name:'Fear',exact:true}).focus();await expect(page.getByRole('button',{name:'Fear',exact:true}).locator('.emotion-tooltip')).toHaveCSS('opacity','1');
 await page.getByRole('button',{name:'Fear',exact:true}).click();
 await expect(page.locator('[data-jev-highlight]').first()).toHaveAttribute('data-jev-highlight','fear trust');
 for(const emotion of readingEmotions)await page.getByRole('button',{name:emotion[0].toUpperCase()+emotion.slice(1),exact:true}).click();
 await expect(page.locator('[data-jev-highlight]')).toHaveCount(0);await expect(page.getByText('All emotions hidden. Enable a circle to show its highlights.')).toBeVisible();
 for(const emotion of readingEmotions)await page.getByRole('button',{name:emotion[0].toUpperCase()+emotion.slice(1),exact:true}).click();
 await page.getByRole('button',{name:'Trust',exact:true}).blur();
 const controls=await page.locator('#config-panel .emotion-controls').boundingBox(),documentPicker=await page.getByLabel('Document',{exact:true}).boundingBox();assert(controls&&documentPicker&&documentPicker.y+documentPicker.height<controls.y,'The document picker sits above the emotion controls');
 assert.equal(await page.locator('#channels .emotion-controls').count(),0,'Config lives apart from the character list');
 await expect(page.locator('#reading-text .emotion-controls')).toHaveCount(0);
 await page.screenshot({path:'/tmp/affect-reader-desktop.png'});
 await page.locator('[data-jev-highlight]').first().click();await expect(page.getByLabel('Emotion inspection',{exact:true})).toHaveCount(0);
 const dial=page.getByLabel('How emotional is JEV',{exact:true});
 const beforeDial=calls.length;
 await dial.focus();await dial.press('Home');
 await expect(page.locator('.emotion-dial-readout')).toContainText('Not at all · JEV highlights from 1.00');
 await expect(page.locator('[data-jev-highlight]')).toHaveCount(0);
 await dial.press('End');
 await expect(page.locator('.emotion-dial-readout')).toContainText('Extremely · JEV highlights from 0.20');
 await expect(page.locator('[data-jev-highlight]').first()).toHaveAttribute('data-jev-highlight','fear trust');
 await page.getByRole('button',{name:'Reset to 0.60'}).click();
 await expect(page.locator('.emotion-dial-readout')).toContainText('Somewhat · JEV highlights from 0.60');
 await expect(page.locator('[data-jev-highlight]').first()).toHaveAttribute('data-jev-highlight','fear trust');
 await page.waitForTimeout(350);assert.equal(calls.length,beforeDial,'Moving the dial must reuse scores');
 // Neither layer is a switch any more: JEV is always on and the NRC lexicon is gone entirely.
 assert.equal(await page.locator('.emotion-controls').getByRole('checkbox').count(),0,'The emotion controls expose no layer switches');
 assert.equal(await page.locator('.emotion-underline, .nrc-legend, [data-nrc-emotions]').count(),0);
 await page.getByLabel('Document',{exact:true}).selectOption('alice-in-wonderland');await expect(page.locator('.passage')).toHaveCount(75);await expect.poll(()=>calls.some(c=>c.layer==='document:alice-in-wonderland')).toBe(true);
 await page.setViewportSize({width:390,height:844});await page.goto(base);await page.locator('[data-emotion-id]').last().waitFor();await expect(page.locator('[data-jev-highlight]').first()).toBeVisible();
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'/tmp/affect-reader-mobile.png'});
 // Three mobile drawers: config, characters, map. Only characters keeps the map strip visible.
 const strip=()=>page.locator('#book-map').evaluate(el=>el.getBoundingClientRect().width);
 await page.getByRole('button',{name:'Config',exact:true}).click();
 await expect(page.getByRole('group',{name:'Visible emotions'})).toBeVisible();
 await expect(page.getByLabel('How emotional is JEV',{exact:true})).toBeVisible();
 await expect(page.getByLabel('Document',{exact:true})).toBeVisible();
 assert.equal(await strip(),0,'Config hides the preview map');
 await page.getByRole('button',{name:'Fear',exact:true}).click();await expect(page.getByRole('button',{name:'Fear',exact:true})).toHaveAttribute('aria-pressed','false');
 await page.screenshot({path:'/tmp/affect-reader-mobile-config.png'});
 await page.getByRole('button',{name:'Close config'}).click();
 await page.getByRole('button',{name:'Characters',exact:true}).click();
 await expect(page.locator('#channels .channel-card').first()).toBeVisible();
 await expect(page.getByRole('button',{name:'Next passage'})).toBeVisible();
 await expect(page.locator('#channels .emotion-controls')).toHaveCount(0);
 assert(await strip()>0,'The characters drawer keeps the preview map visible');
 await page.screenshot({path:'/tmp/affect-reader-mobile-sidebar.png'});
 await page.getByRole('button',{name:'Close characters'}).click();
 await page.getByRole('button',{name:'Map',exact:true}).click();await expect(page.locator('#book-map .progress-track')).toBeVisible();await expect(page.locator('#book-map').getByText('Source and research notes on GitHub')).toBeVisible();await page.getByRole('button',{name:'Close map'}).click();
 await page.setViewportSize({width:320,height:740});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 assert.equal((await page.request.post(`${base}/api/emotions`,{headers:{Origin:base},data:{}})).status(),400);
 assert.equal((await page.request.post(`${base}/api/emotions`,{headers:{Origin:'https://foreign.example'},data:{}})).status(),403);
 assert.equal((await page.request.get(`${base}/api/emotions?layer=../../.env`)).status(),400);
 assert.equal((await page.request.post(`${base}/api/emotions`,{data:{layer:'mentions',sourceKey:'stale',sentenceId:'bad'}})).status(),409);
 assert.deepEqual(errors,[]);console.log(JSON.stringify({status:'passed',mockedJev:true,calls:calls.length,maxConcurrent:maxActive,checks:'viewport queue, retry, reuse, emotionality dial, highlight tooltip, no click inspector, no NRC layer, mobile config/characters/map drawers, editions, desktop/mobile, API validation'}));
}finally{await browser.close();}
